### ISSUE TITLE
Build error with gcc 9 and qt 5.12

### ISSUE THREAD

**Issue by rezso** [samsonwang/LaunchyQt#15]
**Describe the bug**
linux/AppLinux.cpp: In member function ‘virtual void launchy::AppLinux::alterItem(launchy::CatItem*)’:
linux/AppLinux.cpp:163:52: error: incompatible types in assignment of ‘QString’ to ‘QString [2]’
  163 |         item->searchName = item->shortName.toLower();

**To Reproduce**
Try to build with gcc 9.1.0

**Expected behavior**
Successful build.

**Desktop (please complete the following information):**
 - Operation System: Linux 64 bit
 - Launchy Version: 3.0.9

**Comment by rezso** [comment]
https://github.com/samsonwang/LaunchyQt/commit/6495c60f385cb868c02b676937ca068514b6c12e solves the incompatible types error, but causes an another error:

linux/AppLinux.cpp: In member function ‘virtual void launchy::AppLinux::alterItem(launchy::CatItem*)’:
linux/AppLinux.cpp:169:26: error: ‘LOWER’ was not declared in this scope
  169 |         item->searchName[LOWER] = item->shortName.toLower();
      |                          ^~~~~
linux/AppLinux.cpp:170:26: error: ‘TRANS’ was not declared in this scope
  170 |         item->searchName[TRANS] = CatItem::convertSearchName(item->searchName[LOWER]);
      |                          ^~~~~

**Comment by samsonwang** [comment]
Thanks for your feedback :)
I just changed my laptop, and lost the linux environment. So I didn't test 6495c60.
I need more time to setup a linux environment.

**Comment by samsonwang** [comment]
I just fix the code according to your feedback.
Hope f3b4b59 can solve your problem.

**Comment by rezso** [comment]
https://github.com/samsonwang/LaunchyQt/commit/f3b4b598126396cbc7d6bea7cb35b61819f6ca79 is solved the compilation error, but I get an linker error now:

`/usr/bin/ld: build/main.o: in function `main':
main.cpp:(.text.startup+0x382): undefined reference to `launchy::createLaunchyWidget(QFlags<launchy::CommandFlag>)'`

**Comment by samsonwang** [comment]
Finally, I setup my linux environment, and fixed this problem in d79ccab .
I made a successful build on CentOS7, gcc4.8.5, qt5.11.1 and python3.6 .

**Comment by rezso** [comment]
Thank you, I succesfully built launchy with gcc 9.1.0, qt 5.12 and python 3.7.

**Comment by rezso** [comment]
qmake doesn't installs liblaunchy and libpluginpy after build:

`make
	INSTALL_ROOT=/var/uhubuild/work/install
	PERL_INSTALL_ROOT=/var/uhubuild/work/install
	prefix=/var/uhubuild/work/install/usr
	mandir=/var/uhubuild/work/install/usr/share/man
	infodir=/var/uhubuild/work/install/usr/share/info
	localstatedir=/var/uhubuild/work/install/var
	sysconfdir=/var/uhubuild/work/install/etc
	install
cd src/lib/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /var/uhubuild/work/compile/src/lib/lib.pro ) && make -f Makefile install
make[1]: Entering directory '/var/uhubuild/work/compile/src/lib'
make -f Makefile.Release install
make[2]: Entering directory '/var/uhubuild/work/compile/src/lib'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/var/uhubuild/work/compile/src/lib'
make[1]: Leaving directory '/var/uhubuild/work/compile/src/lib'
cd src/pluginpy/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /var/uhubuild/work/compile/src/pluginpy/pluginpy.pro ) && make -f Makefile install
make[1]: Entering directory '/var/uhubuild/work/compile/src/pluginpy'
make -f Makefile.Release install
make[2]: Entering directory '/var/uhubuild/work/compile/src/pluginpy'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/var/uhubuild/work/compile/src/pluginpy'
make[1]: Leaving directory '/var/uhubuild/work/compile/src/pluginpy'
`

**Comment by rezso** [comment]
All problems solved, I close this issue. Thanks.
